export const authTypes={
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILED:"LOGIN_FAILED",

  GET_CREDEN_REQ:"GET_CREDEN_REQ",
  GET_CREDEN_SUCCESS:"GET_CREDEN_SUCCESS",
  GET_CREDEN_FAIL:"GET_CREDEN_FAIL",

  LOGOUT_REQ:"LOGOUT_REQ",
  LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
  GET_PASSWORD_RESET_CODE:"GET_PASSWORD_RESET_CODE"
}

export const adminProductTypes={
  ADD_PRODUCT_REQ:"ADD_PRODUCT_REQ",
  ADD_PRODUCT_SUCCESS:"ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILED:"ADD_PRODUCT_FAILED",

  EDIT_PRODUCT_REQ:"EDIT_PRODUCT_REQ",
  EDIT_PRODUCT_SUCCESS:"EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_FAILED:"EDIT_PRODUCT_FAILED",

  DELETE_PRODUCT_REQ:"DELETE_PRODUCT_REQ",
  DELETE_PRODUCT_SUCCESS:"DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILED:"DELETE_PRODUCT_FAILED",
}

export const clientProductTypes={
  GET_PRODUCTS_REQ:"GET_PRODUCTS_REQ",
  GET_PRODUCTS_SUCCESS:"GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL:"GET_PRODUCTS_FAIL",

  EDIT_SIZE_TO_PRODUCT:"EDIT_SIZE_TO_PRODUCT",
  DELETE_SIZE_TO_PRODUCT:"DELETE_SIZE_TO_PRODUCT",
  DEFAULT_PRODUCT_DATA:"DEFAULT_PRODUCT_DATA",
  EDIT_INGRIDIENTS:"EDIT_INGRIDIENTS",
  REMOVE_INGRIDIENTS:"REMOVE_INGRIDIENTS",
  EDIT_PRODUCT_QTY:"EDIT_PRODUCT_QTY"
}

export const cartTypes={
  GET_CART_DATA:"GET_CART_DATA",
  EDIT_CART_REQ:"EDIT_CART_REQ",
  EDIT_CART_SUCCESS:"EDIT_CART_SUCCESS",
  EDIT_CART_ERR:"EDIT_CART_ERR",
  DEL_CART_REQ:"DEL_CART_REQ",
  DEL_CART_SUCCESS:"DEL_CART_SUCCESS",
  DEL_CART_ERR:"DEL_CART_ERR",
  GET_CART_REQ:"GET_CART_REQ",
  EDIT_CART_LENGTH:"EDIT_CART_LENGTH",
  EDIT_CART_AMOUNT:"EDIT_CART_AMOUNT",
  CART_DATA_RESET:"CART_DATA_RESET"
}
export const siteTypes={
  DISPLAY_SIDEBAR:"DISPLAY_SIDEBAR",
  HIDE_SIDEBAR:"HIDE_SIDEBAR",
  DISPLAY_AD_SIDEBAR:"DISPLAY_AD_SIDEBAR",
  HIDE_AD_SIDEBAR:"HIDE_AD_SIDEBAR",
  TAB_CHANGE:"TAB_CHANGE"
}

export const orderTypes={
  SET_DELIVERY_ADDRESS:"SET_DELIVERY_ADDRESS",
  SET_PAYMENT_OPTION:"SET_PAYMENT_OPTION"
}
