import React from 'react'
import Head from 'next/head'
const HeadTag = ({headLine}) => {
    return (
      <Head>
        <title>{headLine}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.ico" />
      </Head>
    )
}

export default HeadTag
