import Head from 'next/head'
import Image from 'next/image'
import Featured from "../components/Featured"
import PizzaList from "../components/PizzaList"
import axios from "axios"
import {useSelector,useDispatch} from "react-redux"
import {useEffect} from "react"
import {getAuthData} from "../redux/actions/auth"
import {clientProductTypes} from "../redux/types"
export default function Home({data}) {
  console.log(data)

  const authUser=useSelector(state=>state.authReducer.authUser)
  const dispatch=useDispatch()
  useEffect(()=>{
    const status=dispatch(getAuthData())
    if(!status){
        router.push("/auth/login")
    }
    dispatch({type:clientProductTypes.GET_PRODUCTS_SUCCESS,payload:data?.products})
  },[])

  return (
    <div>
      <Head>
        <title>Pizza Hut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.ico" />
      </Head>
      <Featured/>
      <PizzaList/>
    </div>
  )
}

export async function getStaticProps(){
  try{
    const aproducts=await fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/products`,{
              headers: {
                Accept: "application/json",
                "Content-Type": "application/json"
              }})
    const products=await aproducts.json()
    console.log(products)

    return{
      props:{
        data:products
      },
      revalidate:100
    }

  }catch(err){

  }
}
